import type { CinemaScenario } from '../types';

// s01 — Rooftop turbulence.
// Teaches: parapet-shed eddies drop mean speed and inject high-frequency gusts
// that make small rotors hunt in yaw and stall intermittently.
export const scenarioRooftop: CinemaScenario = {
  id: 's01-rooftop',
  nameUA: 'Дах багатоповерхівки',
  nameEN: 'Rooftop turbulence',
  synopsisUA: 'Парапет зриває вихори — низька середня швидкість, різкі пориви, часті часткові зриви.',
  synopsisEN: 'Parapet sheds eddies — low mean speed, sharp gusts, intermittent partial stall.',
  duration: 30,
  site: 'roof',
  stage: 'rooftop',
  reference: 'IEC 61400-2 §11.9 (small-wind rooftop turbulence)',
  keyframes: [
    { t: 0,  windSpeed: 4,  tsr: 4, turbulence: 0.05, target: 'inflow',
      chapter: { ua: 'Турбулентність над дахом', en: 'Rooftop turbulence' },
      camera: { pos: [6, 2, 6], look: [0, 0, 0], lerp: 0.04 },
      hud: { formula: 'TI = σ_V / V̄', metrics: [
        { label: 'V̄', value: '4.0', unit: 'm/s' }, { label: 'TI', value: '5', unit: '%' },
      ] },
      message: { ua: 'Початок: спокійний потік 4 м/с, парапет попереду.',
                 en: 'Start: calm 4 m/s inflow, parapet upstream.' } },
    { t: 4,  windSpeed: 4.5, turbulence: 0.15, target: 'inflow',
      vfx: [{ kind: 'arrow', pos: [0, 0.4, -3], dir: [0, 1.2, 1.5], color: '#7be7ff', ttl: 5, label: 'shear' }],
      message: { ua: 'Парапет зриває дрібні вихори — з’являється зсув швидкості по висоті.',
                 en: 'Parapet begins shedding eddies — vertical shear appears.' } },
    { t: 9,  windSpeed: 6, tsr: 4.5, turbulence: 0.30, target: 'blade',
      vfx: [{ kind: 'pulse', pos: [0, 0.3, -2.5], radius: 0.4, color: '#66e8ff', ttl: 1.5 }],
      hud: { metrics: [ { label: 'V̄', value: '6.0', unit: 'm/s' }, { label: 'TI', value: '30', unit: '%', warn: true } ] },
      message: { ua: 'Порив 6 м/с піднімає TSR, але корінь лопаті входить у зону зриву.',
                 en: 'A 6 m/s gust lifts TSR, but the blade root dips into stall.' } },
    { t: 14, windSpeed: 3.5, tsr: 3.5, turbulence: 0.35, target: 'blade',
      viewMode: 'stall',
      message: { ua: 'Швидкість падає — ротор інерцією тримає обʼєм обертання.',
                 en: 'Speed drops — rotor inertia carries the rpm briefly.' } },
    { t: 18, windSpeed: 8, tsr: 5, turbulence: 0.45, failureBoost: 0.25, target: 'wake',
      vfx: [
        { kind: 'pulse', pos: [0, 0.3, -2], radius: 0.5, color: '#ffaa44', ttl: 1.2 },
        { kind: 'highlightBlade', index: 0, ttl: 1.5 },
      ],
      hud: { metrics: [ { label: 'V̄', value: '8.0', unit: 'm/s', warn: true }, { label: 'TI', value: '45', unit: '%', warn: true } ] },
      message: { ua: 'Різкий гст 8 м/с: слід стає нестабільним, зʼявляється 1P-вібрація.',
                 en: 'Sharp 8 m/s gust: wake destabilises, 1P vibration builds.' } },
    { t: 23, windSpeed: 5.5, tsr: 4.5, turbulence: 0.55, failureBoost: 0.5, target: 'blade',
      viewMode: 'stress',
      vfx: [{ kind: 'shockwave', pos: [0, 0, 0], radius: 0.5, color: '#ff5533', ttl: 1.5 }],
      message: { ua: 'Перевантаження на корені — треба зменшити TSR або підняти щоглу.',
                 en: 'Root overload — reduce TSR or raise the mast.' } },
    { t: 28, windSpeed: 5,  tsr: 4, turbulence: 0.4,  failureBoost: 0.1, target: null,
      viewMode: 'solid',
      chapter: { ua: 'Висновок', en: 'Takeaway' },
      hud: { metrics: [ { label: 'Yield loss', value: '30–50', unit: '%', warn: true } ] },
      message: { ua: 'Висновок: rooftop TI ~40 % їсть 30–50 % річної виробітки.',
                 en: 'Takeaway: rooftop TI ~40 % costs 30–50 % of annual yield.' } },
    { t: 30, windSpeed: 5,  tsr: 4, turbulence: 0.4,  failureBoost: 0 },
  ],
};
