import type { CinemaScenario } from '../types';

// s01 — Rooftop turbulence.
// Teaches: parapet-shed eddies drop mean speed and inject high-frequency gusts
// that make small rotors hunt in yaw and stall intermittently.
export const scenarioRooftop: CinemaScenario = {
  id: 's01-rooftop',
  nameUA: 'Дах багатоповерхівки',
  nameEN: 'Rooftop turbulence',
  synopsisUA: 'Парапет зриває вихори — низька середня швидкість, різкі пориви, часті часткові зриви.',
  synopsisEN: 'Parapet sheds eddies — low mean speed, sharp gusts, intermittent partial stall.',
  duration: 30,
  site: 'roof',
  stage: 'rooftop',
  composition: { framing: 'medium', fov: 46, lookBias: [0, 0.05, 0], minDistanceR: 1.2, floorClearance: 0.15 },
  reference: 'IEC 61400-2 §11.9 (small-wind rooftop turbulence)',
  anchor: [0, 0, 0],
  steps: [
    {
      id: 'inflow', at: 0,
      titleUA: 'Набігаючий потік', titleEN: 'Inflow',
      bodyUA: 'Спокійні 4 м/с підходять до парапету. Профіль швидкості ще логарифмічний і рівний.',
      bodyEN: 'A calm 4 m/s stream approaches the parapet. The profile is still a clean log law.',
      marks: [
        { kind: 'flow', pos: [-2.6, -0.2, 0], dir: [2.2, 0, 0], color: '#7be7ff', speed: 1, label: 'V = 4 m/s' },
        { kind: 'point', pos: [-1.6, -0.9, 0], color: '#8ef7c4', label: 'Parapet', sub: 'separation edge' },
      ],
    },
    {
      id: 'separation', at: 4,
      titleUA: 'Зона відриву', titleEN: 'Separation bubble',
      bodyUA: 'За парапетом потік відривається: усередині бульбашки швидкість реверсує, а TI зростає втричі.',
      bodyEN: 'Flow detaches behind the parapet: inside the bubble the streamwise speed reverses and TI triples.',
      marks: [
        { kind: 'zone', pos: [-0.6, -0.6, 0], radius: 1.1, height: 0.8, color: '#ffaa44', label: 'recirculation' },
        { kind: 'flow', pos: [-0.2, -0.35, 0], dir: [-0.9, 0.5, 0], color: '#ffaa44', speed: 1.6 },
      ],
    },
    {
      id: 'stall', at: 9,
      titleUA: 'Зрив на корені', titleEN: 'Root stall',
      bodyUA: 'Порив піднімає кут атаки на корені понад критичний — там зʼявляється локальний зрив.',
      bodyEN: 'The gust drives root angle of attack past critical — a local stall cell appears.',
      marks: [
        { kind: 'zone', pos: [0, 0, 0], radius: 0.55, height: 0.5, color: '#ff7a00', label: 'stall cell' },
        { kind: 'point', pos: [0.35, 0.1, 0], color: '#ff7a00', label: 'α > α_stall', sub: 'blade root' },
      ],
    },
    {
      id: 'loads', at: 18,
      titleUA: 'Навантаження 1P', titleEN: '1P loading',
      bodyUA: 'Нерівномірний потік по диску дає циклічне навантаження раз на оберт — це і є 1P-вібрація.',
      bodyEN: 'Uneven inflow across the disc loads each blade once per revolution — the classic 1P vibration.',
      marks: [
        { kind: 'zone', pos: [0, 0, 0], radius: 1.05, height: 0.12, color: '#a78bfa', label: 'rotor disc' },
        { kind: 'span', from: [0, -1, 0], to: [0, 1, 0], color: '#c9b7ff', label: 'ΔV across disc' },
      ],
    },
    {
      id: 'takeaway', at: 28,
      titleUA: 'Висновок', titleEN: 'Takeaway',
      bodyUA: 'Підняти щоглу вище 1.5·H будівлі — і ротор виходить із зони відриву майже повністю.',
      bodyEN: 'Raise the mast above 1.5·H of the building and the rotor clears the separation zone almost entirely.',
      marks: [
        { kind: 'span', from: [0, -1.2, 0], to: [0, 1.6, 0], color: '#8ef7c4', label: 'mast height 1.5·H' },
      ],
    },
  ],
  keyframes: [
    { t: 0,  windSpeed: 4,  tsr: 4, turbulence: 0.05, target: 'inflow',
      chapter: { ua: 'Турбулентність над дахом', en: 'Rooftop turbulence' },
      camera: { pos: [6, 2, 6], look: [0, 0, 0], lerp: 0.04 },
      hud: { formula: 'TI = σ_V / V̄', metrics: [
        { label: 'V̄', value: '4.0', unit: 'm/s' }, { label: 'TI', value: '5', unit: '%' },
      ] },
      message: { ua: 'Початок: спокійний потік 4 м/с, парапет попереду.',
                 en: 'Start: calm 4 m/s inflow, parapet upstream.' } },
    { t: 4,  windSpeed: 4.5, turbulence: 0.15, target: 'inflow',
      vfx: [{ kind: 'arrow', pos: [0, 0.4, -3], dir: [0, 1.2, 1.5], color: '#7be7ff', ttl: 5, label: 'shear' }],
      message: { ua: 'Парапет зриває дрібні вихори — з’являється зсув швидкості по висоті.',
                 en: 'Parapet begins shedding eddies — vertical shear appears.' } },
    { t: 9,  windSpeed: 6, tsr: 4.5, turbulence: 0.30, target: 'blade',
      vfx: [{ kind: 'pulse', pos: [0, 0.3, -2.5], radius: 0.4, color: '#66e8ff', ttl: 1.5 }],
      hud: { metrics: [ { label: 'V̄', value: '6.0', unit: 'm/s' }, { label: 'TI', value: '30', unit: '%', warn: true } ] },
      message: { ua: 'Порив 6 м/с піднімає TSR, але корінь лопаті входить у зону зриву.',
                 en: 'A 6 m/s gust lifts TSR, but the blade root dips into stall.' } },
    { t: 14, windSpeed: 3.5, tsr: 3.5, turbulence: 0.35, target: 'blade',
      viewMode: 'stall',
      message: { ua: 'Швидкість падає — ротор інерцією тримає обʼєм обертання.',
                 en: 'Speed drops — rotor inertia carries the rpm briefly.' } },
    { t: 18, windSpeed: 8, tsr: 5, turbulence: 0.45, failureBoost: 0.25, target: 'wake',
      vfx: [
        { kind: 'pulse', pos: [0, 0.3, -2], radius: 0.5, color: '#ffaa44', ttl: 1.2 },
        { kind: 'highlightBlade', index: 0, ttl: 1.5 },
      ],
      hud: { metrics: [ { label: 'V̄', value: '8.0', unit: 'm/s', warn: true }, { label: 'TI', value: '45', unit: '%', warn: true } ] },
      message: { ua: 'Різкий гст 8 м/с: слід стає нестабільним, зʼявляється 1P-вібрація.',
                 en: 'Sharp 8 m/s gust: wake destabilises, 1P vibration builds.' } },
    { t: 23, windSpeed: 5.5, tsr: 4.5, turbulence: 0.55, failureBoost: 0.5, target: 'blade',
      viewMode: 'stress',
      vfx: [{ kind: 'shockwave', pos: [0, 0, 0], radius: 0.5, color: '#ff5533', ttl: 1.5 }],
      message: { ua: 'Перевантаження на корені — треба зменшити TSR або підняти щоглу.',
                 en: 'Root overload — reduce TSR or raise the mast.' } },
    { t: 28, windSpeed: 5,  tsr: 4, turbulence: 0.4,  failureBoost: 0.1, target: null,
      viewMode: 'solid',
      chapter: { ua: 'Висновок', en: 'Takeaway' },
      hud: { metrics: [ { label: 'Yield loss', value: '30–50', unit: '%', warn: true } ] },
      message: { ua: 'Висновок: rooftop TI ~40 % їсть 30–50 % річної виробітки.',
                 en: 'Takeaway: rooftop TI ~40 % costs 30–50 % of annual yield.' } },
    { t: 30, windSpeed: 5,  tsr: 4, turbulence: 0.4,  failureBoost: 0 },
  ],
};
